if (!require("tidytext")) install.packages("tidytext")
library(tidytext)
if (!require("qdapRegex")) install.packages("qdapRegex")
library(qdapRegex)
if (!require("stringr")) install.packages("stringr")
library(stringr)
if (!require("tm")) install.packages("tm")
library(tm)

clean = function(x){
        #Now we will reduce the dimension through data cleaning, we will remove puntuations and replace some expressions:
        #replace negation
        df = tolower(x)
        clean = gsub("can't","cannot", df )
        clean = gsub("won't","will not", clean )
        clean = gsub("n't"," not", clean )
        
        clean = gsub("c\\(\""," ", clean)
        clean = gsub("\\\\n"," ", clean )
        clean = gsub("\\n"," ", clean )
        
        #replace i.e and e.g
        #clean= "(i.e this is small"
        clean = gsub(" i.e ","that is", clean, fixed = TRUE )
        clean = gsub(" e.g ","for example", clean, fixed = TRUE )
        clean= tm::removePunctuation(clean)
        #some words
        clean = gsub("why"," why", clean )
        clean = gsub("whyd","why", clean )
        clean = gsub("iggers","igger", clean )
        clean = gsub("iggas","igger", clean )
        clean = gsub("iggaz","igger", clean )
        #clean = gsub("igga","igger", clean )
        clean = gsub("igga","igger", clean )
        clean = gsub("l33ers","igger", clean )
        clean = gsub("mothjer","mother", clean )
        clean = gsub("tommy2010"," ", clean )
        clean = gsub("bunksteve"," ", clean )
        clean = gsub("jim wales "," ", clean, fixed = TRUE )
        clean = gsub("fack","fuck", clean)
        clean = gsub("fuckeeed", "fucked", clean)
        clean = gsub("supertr0ll"," ", clean )
        clean = gsub("itsuck","it suck", clean)
        clean = gsub("cocksucker","cock suck", clean)
        clean = gsub("dickhead","dick head", clean)
        clean = gsub(" utc "," ", clean)
        clean = gsub("criminalwar", "criminal war", clean)
        clean = gsub("yourselfgo", "yourself go", clean)
        clean = gsub("offfuck", "off fuck", clean)
        clean = gsub("cocksucker", "cock sucker", clean)
        clean = gsub("marcolfuck", "marcol fuck", clean)
        clean = gsub("fucking", " fucking ", clean)
        clean = gsub("fack", "fuck", clean)
        clean = gsub("phuq", "fuck", clean)
        clean = gsub("proassadhanibal911you're", "you are", clean)
        clean = gsub("securityfuck", "security fuck", clean)
        clean = gsub("bitches", "bitch", clean)
        clean = gsub("njgw", "nigger", clean)
        clean = gsub("centraliststupid", "centralist stupid", clean)
        clean = gsub("dickhead", "dick head", clean)
        clean = gsub("buttsecks", "butt sex", clean)
        clean = gsub("youfuck", "you fuck", clean)
        clean = gsub("bitchfuck", "bich fuck", clean)
        clean = gsub("assfuck", "ass fuck", clean)
        clean = gsub("fucksex", "fuck sex", clean)
        clean = gsub("penissmall", "small penis", clean)
        clean = gsub("pneis", "penis", clean)
        clean = gsub("pennnis", "penis", clean)
        clean = gsub("noobs", "noob", clean)
        clean = gsub("ancestry", " ancestry ", clean)
        clean = gsub("ancestryfuckoffjewis", "ancestry fuck off jewish", clean)
        clean = gsub("sucku", "suck you", clean)
        clean = gsub("cocksucking", "cock sucking", clean)
        clean = gsub("shitfuck", "shit fuck", clean)
        clean = gsub("sexsex", "sex sex", clean)
        clean = gsub("itsuck", "it suck", clean)
        clean = gsub("biznitch", "bitch snitch", clean)
        clean = gsub("cuntbag", "cunt bag", clean)
        clean = gsub("spics", "spic", clean)
        clean = gsub("rvv", "reverted vandalism", clean)
        clean = gsub("haahhahahah", "haha haha", clean)
        clean = gsub("yaaa", "yaa", clean)
        clean = gsub("yaaaaah", "yaa", clean)
        clean = gsub("youbollocks", "you bollocks", clean)
        clean = gsub("fartchina", "fart china", clean)
        clean = gsub("fggt", "faggot", clean)
        clean = gsub("faggots", "faggot", clean)
        clean = gsub("cougaryou", "cougar you", clean)
        clean = gsub("gayfrozen", "gay frozen", clean)
        clean = gsub("gayfag", "gay faggot", clean)
        clean = gsub("faggot", " faggot ", clean)
        clean = gsub("bestfrozen", "best frozen", clean)
        clean = gsub("faggotjéské", "faggot jéské", clean)
        clean = gsub("kkkkkk", "ok", clean)
        clean = gsub("uuuuuu", "uu", clean)
        clean = gsub("republicango", "republican go", clean)
        clean = gsub("basteredbastered", "basterds basterds", clean)
        clean = gsub("ashol", "asshole", clean)
        clean = gsub("wikiprojects", "wikipedia projects", clean)
        clean = gsub("wikiproject", "wikipedia project", clean)
        clean = gsub("wikipedia's", "wikipedia", clean)
        clean = gsub("wikipedian", "wikipedians", clean)
        clean = gsub("wikipeidia", "wikipedia", clean)
        clean = gsub("wikipedian", "wikipedians", clean)
        clean = gsub("wikinazi", "wikipedia nazi", clean)
        clean = gsub("misterwiki", "mister wikipedia", clean)
        clean = gsub("ashol", "asshole", clean)
        clean = gsub("assholeyou", "asshole", clean)
        #clean = gsub("cocksucker","it suck", clean)
        #clean = gsub("supertr0ll","super troll", clean, fixed = TRUE )
        
        #Enlever les dieses
        #deja fait dans le .rds
        
        #Enlever la ponctuation
        clean = gsub("[[:punct:]]"," ", clean)
        
        #Enlever les espaces blancs à la fin
        #clean_com = gsub("  ", "", clean_com)
        
        #Probleme lié aà l'encodage
        clean = gsub("'", " ", clean)
        clean = gsub("[^[:alnum:]///' ]", " ", clean)
        
        #clean = stripWhitespace(clean)
        clean = rm_white(clean)
        
        #We limit the length of a comment to maxl
        #clean =substring(clean,1,maxl)
        
        return(clean)
        
}


length_comments = function(x){
        comment = strsplit(x, " ")
        l_comment = comment %>%
                map(length) %>%
                reduce(rbind)
        l_unique = comment %>%
                map(unique) %>%
                map(length) %>%
                reduce(rbind)
        
        res = data.frame(l_comment = l_comment, l_unique = l_unique, unique_per_l = l_unique/l_comment, row.names = NULL )
        
        return(res)
}      


unknwon_words = function(x,dic=wgt$word){
        comment = strsplit(x, " ")
        comment = comment %>%
                map( function(y){
                        res = y [!y %in% dic] 
                        
                }) 
        
        return(unlist(comment))
}

preclean = function(x){
        df = x
        #Enlever les dieses
        #deja fait dans le .rds
        preclean = gsub("c\\(\""," ", df)
        preclean = gsub("\\\\n"," ", preclean )
        preclean = gsub("\\n"," ", preclean )
        preclean = gsub("“|„"," ", preclean )
        preclean = removePunctuation(preclean, preserve_intra_word_contractions = TRUE)
        preclean = stripWhitespace(preclean)
        return(preclean)
}

freqWord = function(x){
        as.data.frame(table(x)) %>%
                arrange(desc(Freq)) %>%
                mutate(type=length(x), total=sum(Freq)) %>%
                filter(Freq>10 & length(x)>0) %>%
                rename(word=x)
}

separate = function(x){
        #df = x  %>% select(comments) 
        #separate = unlist(stringr::str_split(df$comments," "))
        #separate =substring(x,1,300)
        separate = stringr::str_split(x," ") %>%
                unlist()
        #word = data.frame(word= separate )
        
        
        separate = stringr::str_split(separate," ") %>%
                unlist()
        separate = trimws(separate)
        
        return(separate)
}

tf_idf_words = function(x){
        comment = strsplit(x, " ")
        comment = comment %>%
                map( function(y){
                        res = y [y %in% tf_idf_vocab #& nchar(y)>1
                                 ] 
                        res = paste(res, collapse = " ")
                }) 
        
        return(unlist(comment))
}

library(qdapRegex)
sms_vocab = function(x){
        df = sub("{1}", " ", x)
        df = gsub( " aren't " , " are not " , df, ignore.case = TRUE)
        df = gsub( " can't " , " cannot " , df, ignore.case = TRUE)
        df = gsub( " couldn't " , " could not " , df, ignore.case = TRUE)
        df = gsub( " didn't " , " did not " , df, ignore.case = TRUE)
        df = gsub( " doesn't " , " does not " , df, ignore.case = TRUE)
        df = gsub( " don't " , " do not " , df, ignore.case = TRUE)
        df = gsub( " hadn't ", " had not ", df, ignore.case = TRUE)
        df = gsub( " hasn't ", " has not ", df, ignore.case = TRUE)
        df = gsub( " haven't ", " have not ", df, ignore.case = TRUE)
        df = gsub( " he'd ", " he would ", df, ignore.case = TRUE)
        df = gsub( " he'll ", " he will ", df, ignore.case = TRUE)
        df = gsub( " he's ", " he is ", df, ignore.case = TRUE)
        df = gsub( " i'd ", " I would ", df, ignore.case = TRUE)
        df = gsub( " i'd ", " I had ", df, ignore.case = TRUE)
        df = gsub( " i'll ", " I will ", df, ignore.case = TRUE)
        df = gsub( " i'm ", " I am ", df, ignore.case = TRUE)
        df = gsub( " isn't ", " is not ", df, ignore.case = TRUE)
        df = gsub( " it's ", " it is ", df, ignore.case = TRUE)
        df = gsub( " it'll ", " it will ", df, ignore.case = TRUE)
        df = gsub( " i've ", " I have ", df, ignore.case = TRUE)
        df = gsub( " let's ", " let us ", df, ignore.case = TRUE)
        df = gsub( " mightn't ", " might not ", df, ignore.case = TRUE)
        df = gsub( " mustn't ", " must not ", df, ignore.case = TRUE)
        df = gsub( " shan't ", " shall not ", df, ignore.case = TRUE)
        df = gsub( " she'd ", " she would ", df, ignore.case = TRUE)
        df = gsub( " she'll ", " she will ", df, ignore.case = TRUE)
        df = gsub( " she's ", " she is ", df, ignore.case = TRUE)
        df = gsub( " shouldn't ", " should not ", df, ignore.case = TRUE)
        df = gsub( " that's ", " that is ", df, ignore.case = TRUE)
        df = gsub( " there's ", " there is ", df, ignore.case = TRUE)
        df = gsub( " they'd ", " they would ", df, ignore.case = TRUE)
        df = gsub( " they'll ", " they will ", df, ignore.case = TRUE)
        df = gsub( " they're ", " they are ", df, ignore.case = TRUE)
        df = gsub( " they've ", " they have ", df, ignore.case = TRUE)
        df = gsub( " we'd ", " we would ", df, ignore.case = TRUE)
        df = gsub( " we're ", " we are ", df, ignore.case = TRUE)
        df = gsub( " weren't ", " were not ", df, ignore.case = TRUE)
        df = gsub( " we've ", " we have ", df, ignore.case = TRUE)
        df = gsub( " what'll ", " what will ", df, ignore.case = TRUE)
        df = gsub( " what're ", " what are ", df, ignore.case = TRUE)
        df = gsub( " what's ", " what is ", df, ignore.case = TRUE)
        df = gsub( " what've ", " what have ", df, ignore.case = TRUE)
        df = gsub( " where's ", " where is ", df, ignore.case = TRUE)
        df = gsub( " who'd ", " who would ", df, ignore.case = TRUE)
        df = gsub( " who'll ", " who will ", df, ignore.case = TRUE)
        df = gsub( " who're ", " who are ", df, ignore.case = TRUE)
        df = gsub( " who's ", " who is ", df, ignore.case = TRUE)
        df = gsub( " who've ", " who have ", df, ignore.case = TRUE)
        df = gsub( " won't ", " will not ", df, ignore.case = TRUE)
        df = gsub( " wouldn't ", " would not ", df, ignore.case = TRUE)
        df = gsub( " you'd ", " you would ", df, ignore.case = TRUE)
        df = gsub( " you'll ", " you will ", df, ignore.case = TRUE)
        df = gsub( " you're ", " you are ", df, ignore.case = TRUE)
        df = gsub( " you've ", " you have ", df, ignore.case = TRUE)
        df = gsub( " 're ", " are ", df, ignore.case = TRUE)
        df = gsub( " wasn't ", " was not ", df, ignore.case = TRUE)
        df = gsub( " we'll ", " will ", df, ignore.case = TRUE)
        df = gsub( " didn't ", " did not ", df, ignore.case = TRUE)
        
        df = gsub(" abt " , " about ", df,  ignore.case = TRUE)
        df = gsub(" abt2 " , " About to ", df,  ignore.case = TRUE)
        df = gsub(" acc " , " Actually ", df,  ignore.case = TRUE)
        df = gsub(" add " , " Address ", df,  ignore.case = TRUE)
        df = gsub(" afaik " , " As far as I know ", df,  ignore.case = TRUE)
        df = gsub(" afk " , " Away from keyboard ", df,  ignore.case = TRUE)
        df = gsub(" aka " , " Also known as ", df,  ignore.case = TRUE)
        df = gsub(" asap " , " As soon as possible ", df,  ignore.case = TRUE)
        df = gsub(" asl " , " Age, sex, location ", df,  ignore.case = TRUE)
        df = gsub(" atm " , " At the moment ", df,  ignore.case = TRUE)
        df = gsub(" b " , " Bisexual ", df,  ignore.case = TRUE)
        df = gsub(" bb " , " Baby ", df,  ignore.case = TRUE)
        df = gsub(" b4 " , " Before ", df,  ignore.case = TRUE)
        df = gsub(" bc " , " Because ", df,  ignore.case = TRUE)
        df = gsub(" bday " , " Birthday ", df,  ignore.case = TRUE)
        df = gsub(" blates " , " Obviously ", df,  ignore.case = TRUE)
        df = gsub(" bf " , " Best friend ", df,  ignore.case = TRUE)
        df = gsub(" bf4l " , " Best friends for life ", df,  ignore.case = TRUE)
        df = gsub(" bffl " , " Best friends for life ", df,  ignore.case = TRUE)
        df = gsub(" bff " , " Best friends forever ", df,  ignore.case = TRUE)
        df = gsub(" boyf " , " Boyfriend ", df,  ignore.case = TRUE)
        df = gsub(" brb " , " Be right back ", df,  ignore.case = TRUE)
        df = gsub(" btw " , " By the way ", df,  ignore.case = TRUE)
        df = gsub(" cba " , " Can’t be bothered ", df,  ignore.case = TRUE)
        df = gsub(" cmb " , " Call me back ", df,  ignore.case = TRUE)
        df = gsub(" cmon " , " Come on ", df,  ignore.case = TRUE)
        df = gsub(" ctn " , " Can’t talk now ", df,  ignore.case = TRUE)
        df = gsub(" cu " , " See you ", df,  ignore.case = TRUE)
        df = gsub(" cua " , " See you around ", df,  ignore.case = TRUE)
        df = gsub(" cul " , " See you later ", df,  ignore.case = TRUE)
        df = gsub(" cya " , " See ya ", df,  ignore.case = TRUE)
        df = gsub(" diss " , " Disrespect ", df,  ignore.case = TRUE)
        df = gsub(" dkdc " , " Don’t know, don’t care ", df,  ignore.case = TRUE)
        df = gsub(" dl " , " Download ", df,  ignore.case = TRUE)
        df = gsub(" dm " , " Direct Message, a form of private messaging ", df,  ignore.case = TRUE)
        df = gsub(" dnt " , " Don’t ", df,  ignore.case = TRUE)
        df = gsub(" ema " , " Email address ", df,  ignore.case = TRUE)
        df = gsub(" ez " , " Easy ", df,  ignore.case = TRUE)
        df = gsub(" f " , " Female ", df,  ignore.case = TRUE)
        df = gsub(" faq " , " Frequently Asked Questions ", df,  ignore.case = TRUE)
        df = gsub(" fb " , " Facebook ", df,  ignore.case = TRUE)
        df = gsub(" fwd " , " Forward ", df,  ignore.case = TRUE)
        df = gsub(" fyi " , " For your information ", df,  ignore.case = TRUE)
        df = gsub(" g " , " Gay ", df,  ignore.case = TRUE)
        df = gsub(" g2cu " , " Good to see you ", df,  ignore.case = TRUE)
        df = gsub(" g2g " , " Got to go ", df,  ignore.case = TRUE)
        df = gsub(" g2r " , " Got to run ", df,  ignore.case = TRUE)
        df = gsub(" gamer " , " Video game player ", df,  ignore.case = TRUE)
        df = gsub(" gf " , " Girlfriend ", df,  ignore.case = TRUE)
        df = gsub(" gg " , " Good game ", df,  ignore.case = TRUE)
        df = gsub(" gj " , " Good job ", df,  ignore.case = TRUE)
        df = gsub(" gl " , " Good luck ", df,  ignore.case = TRUE)
        df = gsub(" glhf " , " Good luck have fun ", df,  ignore.case = TRUE)
        df = gsub(" gnite " , " Good night ", df,  ignore.case = TRUE)
        df = gsub(" gr8 " , " Great ", df,  ignore.case = TRUE)
        df = gsub(" gratz " , " Congratulations ", df,  ignore.case = TRUE)
        df = gsub(" gtg " , " Got to go ", df,  ignore.case = TRUE)
        df = gsub(" gud " , " Good ", df,  ignore.case = TRUE)
        df = gsub(" h8 " , " Hate ", df,  ignore.case = TRUE)
        df = gsub(" hella " , " Really ", df,  ignore.case = TRUE)
        df = gsub(" hv " , " Have ", df,  ignore.case = TRUE)
        df = gsub(" hw " , " Homework ", df,  ignore.case = TRUE)
        #df = gsub(" i " , " I love you ", df,  ignore.case = TRUE)
        df = gsub(" ib " , " I’m back ", df,  ignore.case = TRUE)
        df = gsub(" ic " , " I see ", df,  ignore.case = TRUE)
        df = gsub(" idc " , " I don’t care ", df,  ignore.case = TRUE)
        df = gsub(" idk " , " I don’t know ", df,  ignore.case = TRUE)
        df = gsub(" iirc " , " If I remember correctly ", df,  ignore.case = TRUE)
        df = gsub(" ik(r) " , " I know right ? ", df, ignore.case = TRUE)
        df = gsub(" ilu " , " I love you ", df, ignore.case = TRUE)
        df = gsub(" ily " , " I love you ", df, ignore.case = TRUE)
        df = gsub(" im " , " Instant message ", df, ignore.case = TRUE)
        df = gsub(" imho " , " In my humble opinion ", df, ignore.case = TRUE)
        df = gsub(" imo " , " In my opinion ", df, ignore.case = TRUE)
        df = gsub(" irl " , " In real life ", df, ignore.case = TRUE)
        df = gsub(" jk " , " Just kidding ", df, ignore.case = TRUE)
        df = gsub(" kewl " , " Cool ", df, ignore.case = TRUE)
        df = gsub(" kthnx " , " OK thanks ", df, ignore.case = TRUE)
        df = gsub(" l " , " Lesbian ", df, ignore.case = TRUE)
        df = gsub(" l8 " , " Late ", df, ignore.case = TRUE)
        df = gsub(" l8r " , " Later ", df, ignore.case = TRUE)
        df = gsub(" lmao " , " Laughing my ass off ", df, ignore.case = TRUE)
        df = gsub(" lol " , " Laugh out loud ", df, ignore.case = TRUE)
        df = gsub(" lolll " , " Laugh out loud a lot ", df, ignore.case = TRUE)
        df = gsub(" luv ya " , " Love you ", df, ignore.case = TRUE)
        df = gsub(" m " , " Male ", df, ignore.case = TRUE)
        df = gsub(" meet irl " , " Meet in real life ", df, ignore.case = TRUE)
        df = gsub(" mkay " , " Mmm okay ", df, ignore.case = TRUE)
        df = gsub(" mmo " , " Massively multiplayer online ", df, ignore.case = TRUE)
        df = gsub(" mmorpg " , " Massively multiplayer online role playing game ", df, ignore.case = TRUE)
        df = gsub(" msg " , " Message ", df, ignore.case = TRUE)
        df = gsub(" mwah " , " To give a kiss ", df, ignore.case = TRUE)
        df = gsub(" n/a " , " Not available or not applicable ", df, ignore.case = TRUE)
        df = gsub(" n2m " , " Nothing too much ", df, ignore.case = TRUE)
        df = gsub(" nbd " , " No big deal ", df, ignore.case = TRUE)
        df = gsub(" ne " , " Any ", df, ignore.case = TRUE)
        df = gsub(" ne1 " , " Anyone ", df, ignore.case = TRUE)
        df = gsub(" nm " , " Not much ", df, ignore.case = TRUE)
        df = gsub(" nm " , " Nothing much ", df, ignore.case = TRUE)
        df = gsub(" nm " , " Never mind ", df, ignore.case = TRUE)
        df = gsub(" n00b " , " noob ", df, ignore.case = TRUE)
        df = gsub(" tr0ll " , " troll ", df, ignore.case = TRUE)
        df = gsub(" np " , " No problem ", df, ignore.case = TRUE)
        df = gsub(" nthng " , " Nothing ", df, ignore.case = TRUE)
        df = gsub(" nvr " , " Never ", df, ignore.case = TRUE)
        df = gsub(" nw " , " No worries ", df, ignore.case = TRUE)
        df = gsub(" oic " , " Oh, I see ", df, ignore.case = TRUE)
        df = gsub(" om " , " Oh my ", df, ignore.case = TRUE)
        df = gsub(" omg " , " Oh my God ", df, ignore.case = TRUE)
        df = gsub(" omw " , " On my way ", df, ignore.case = TRUE)
        df = gsub(" onl " , " Online ", df, ignore.case = TRUE)
        df = gsub(" ot " , " Off topic ", df, ignore.case = TRUE)
        df = gsub(" ova " , " Over ", df, ignore.case = TRUE)
        df = gsub(" peak " , " Unfortunate ", df, ignore.case = TRUE)
        df = gsub(" peeps " , " People ", df, ignore.case = TRUE)
        df = gsub(" pic " , " Picture ", df, ignore.case = TRUE)
        df = gsub(" pir " , " Parent in room ", df, ignore.case = TRUE)
        df = gsub(" pk " , " Player kill ", df, ignore.case = TRUE)
        df = gsub(" pls " , " Please ", df, ignore.case = TRUE)
        df = gsub(" plz " , " Please ", df, ignore.case = TRUE)
        df = gsub(" pm " , " Private Message ", df, ignore.case = TRUE)
        df = gsub(" pmsl " , " Peeing myself laughing ", df, ignore.case = TRUE)
        df = gsub(" pov " , " Point of view ", df, ignore.case = TRUE)
        df = gsub(" ppl " , " People ", df, ignore.case = TRUE)
        df = gsub(" prolly " , " Probably ", df, ignore.case = TRUE)
        df = gsub(" pwn " , " Own ", df, ignore.case = TRUE)
        df = gsub(" pwned " , " Owned ", df, ignore.case = TRUE)
        df = gsub(" qt " , " Cutie ", df, ignore.case = TRUE)
        df = gsub(" qtpi " , " Cutie pie ", df, ignore.case = TRUE)
        df = gsub(" r " , " Are ", df, ignore.case = TRUE)
        df = gsub(" rly " , " Really ", df, ignore.case = TRUE)
        df = gsub(" rofl " , " Rolling on the floor laughing ", df, ignore.case = TRUE)
        df = gsub(" rotfl " , " Rolling on the floor laughing ", df, ignore.case = TRUE)
        df = gsub(" rotl " , " Rolling on the floor laughing ", df, ignore.case = TRUE)
        df = gsub(" rpg " , " Role playing game ", df, ignore.case = TRUE)
        df = gsub(" ru " , " Are you? ", df, ignore.case = TRUE)
        df = gsub(" ruok " , " Are you okay? ", df, ignore.case = TRUE)
        df = gsub(" sec " , " Second ", df, ignore.case = TRUE)
        df = gsub(" skl " , " School ", df, ignore.case = TRUE)
        df = gsub(" smh " , " Shaking my head ", df, ignore.case = TRUE)
        df = gsub(" sms " , " Short Message Service ", df, ignore.case = TRUE)
        #df = gsub(" so " , " Significant other ", df, ignore.case = TRUE)
        df = gsub(" sob " , " Son of a Bitch ", df, ignore.case = TRUE)
        df = gsub(" sos " , " Help ", df, ignore.case = TRUE)
        df = gsub(" spk " , " Speak ", df, ignore.case = TRUE)
        df = gsub(" srs " , " Serious ", df, ignore.case = TRUE)
        df = gsub(" srsbsns " , " Serious business ", df, ignore.case = TRUE)
        df = gsub(" srsly " , " Seriously ", df, ignore.case = TRUE)
        df = gsub(" sry " , " Sorry ", df, ignore.case = TRUE)
        df = gsub(" str8 " , " Straight ", df, ignore.case = TRUE)
        df = gsub(" sup " , " What’s up ", df, ignore.case = TRUE)
        df = gsub(" sux " , " it sucks ", df, ignore.case = TRUE)
        #df = gsub(" swag " , " Boasting about one’s skills or style ", df, ignore.case = TRUE)
        df = gsub(" tc " , " Take care ", df, ignore.case = TRUE)
        df = gsub(" tgif " , " Thank God it’s Friday ", df, ignore.case = TRUE)
        df = gsub(" thanq " , " Thank you ", df, ignore.case = TRUE)
        df = gsub(" thx " , " Thanks ", df, ignore.case = TRUE)
        df = gsub(" tmi " , " Too much information ", df, ignore.case = TRUE)
        df = gsub(" trans " , " Transsexual ", df, ignore.case = TRUE)
        df = gsub(" ttfn " , " Ta-ta for now ", df, ignore.case = TRUE)
        df = gsub(" ttyl " , " Talk to you later ", df, ignore.case = TRUE)
        df = gsub(" tweet " , " Twitter post ", df, ignore.case = TRUE)
        df = gsub(" txt " , " Text ", df, ignore.case = TRUE)
        df = gsub(" ty " , " Thank you ", df, ignore.case = TRUE)
        df = gsub(" u " , " You ", df, ignore.case = TRUE)
        df = gsub(" u2 " , " You too ", df, ignore.case = TRUE)
        df = gsub(" ul " , " Upload ", df, ignore.case = TRUE)
        df = gsub(" ur " , " Your ", df, ignore.case = TRUE)
        df = gsub(" vm " , " Voicemail ", df, ignore.case = TRUE)
        df = gsub(" w@ " , " What? ", df, ignore.case = TRUE)
        df = gsub(" w/ " , " With ", df, ignore.case = TRUE)
        df = gsub(" w/e " , " Whatever or weekend ", df, ignore.case = TRUE)
        df = gsub(" w/o " , " Without ", df, ignore.case = TRUE)
        df = gsub(" w8 " , " Wait ", df, ignore.case = TRUE)
        df = gsub(" wag1 " , " What’s up ", df, ignore.case = TRUE)
        df = gsub(" wbu " , " What about you? ", df, ignore.case = TRUE)
        df = gsub(" wk " , " Week ", df, ignore.case = TRUE)
        df = gsub(" wrk " , " Work ", df, ignore.case = TRUE)
        df = gsub(" wtf " , " What the fuck ", df, ignore.case = TRUE)
        df = gsub(" wtg " , " Way to go ", df, ignore.case = TRUE)
        df = gsub(" WYSIWYG " , " What you see is what you get ", df, ignore.case = TRUE)
        df = gsub(" y? " , " Why? ", df, ignore.case = TRUE)
        df = gsub(" yolo " , " You only live once ", df, ignore.case = TRUE)
        df = gsub(" yr " , " Your ", df, ignore.case = TRUE)
        df = gsub(" yw " , " You’re welcome ", df, ignore.case = TRUE)
        df = gsub(" 2 " , " To ", df, ignore.case = TRUE)
        #df = gsub(" 43305 " , " Twenty-four hours a day, seven days a week ", df, ignore.case = TRUE)
        
        df = gsub(" 143 ", " I love you ", df,  ignore.case = TRUE)
        df = gsub(" 2DAY ", " Today ", df,  ignore.case = TRUE)
        df = gsub(" 4EAE ", " For ever and ever ", df,  ignore.case = TRUE)
        df = gsub(" ADN ", " Any day now ", df,  ignore.case = TRUE)
        df = gsub(" AFAIK ", " As far as I know ", df,  ignore.case = TRUE)
        df = gsub(" AFK ", " Away from keyboard ", df,  ignore.case = TRUE)
        df = gsub(" ATM ", " At the moment ", df,  ignore.case = TRUE)
        df = gsub(" B/C ", " Because ", df,  ignore.case = TRUE)
        df = gsub(" B4 ", " Before ", df,  ignore.case = TRUE)
        df = gsub(" BFN ", " Bye for now ", df,  ignore.case = TRUE)
        df = gsub(" BOL ", " Be on later ", df,  ignore.case = TRUE)
        df = gsub(" BRB ", " Be right back ", df,  ignore.case = TRUE)
        df = gsub(" BTW ", " By the way ", df,  ignore.case = TRUE)
        df = gsub(" DM ", " Direct message ", df,  ignore.case = TRUE)
        df = gsub(" DWBH ", " Don’t worry be happy ", df,  ignore.case = TRUE)
        df = gsub(" F2F or FTF ", " Face to face ", df,  ignore.case = TRUE)
        df = gsub(" FB ", " Facebook ", df,  ignore.case = TRUE)
        df = gsub(" FF ", " Follow Friday ", df,  ignore.case = TRUE)
        df = gsub(" FTL ", " For the loss ", df,  ignore.case = TRUE)
        df = gsub(" FTW ", " For the win ", df,  ignore.case = TRUE)
        df = gsub(" FWB ", "Friends with benefits ", df,  ignore.case = TRUE)
        df = gsub(" FWIW ", " For what it’s worth ", df,  ignore.case = TRUE)
        df = gsub(" FYEO ", " For your eyes only ", df, ignore.case = TRUE)
        df = gsub(" FYI ", " For your information ", df, ignore.case = TRUE)
        df = gsub(" GLHF ", " Good luck, have fun ", df, ignore.case = TRUE)
        df = gsub(" GR8 ", " Great ", df, ignore.case = TRUE)
        df = gsub(" HAK ", " Hugs and kisses ", df, ignore.case = TRUE)
        df = gsub(" HAND ", " Have a nice day ", df, ignore.case = TRUE)
        df = gsub(" HT ", " Hat tip ", df, ignore.case = TRUE)
        df = gsub(" HTH ", " Hope this helps ", df, ignore.case = TRUE)
        df = gsub(" IANAL ", " I am not a lawyer ", df, ignore.case = TRUE)
        df = gsub(" IDK ", " I don’t know ", df, ignore.case = TRUE)
        df = gsub(" IIRC ", " If I remember correctly ", df, ignore.case = TRUE)
        df = gsub(" IKR ", " I know right ", df, ignore.case = TRUE)
        df = gsub(" ILY ", " I love you ", df, ignore.case = TRUE)
        df = gsub(" ILU ", " I love you ", df, ignore.case = TRUE)
        df = gsub(" IMHO ", " In my honest opinion ", df, ignore.case = TRUE)
        df = gsub(" IMO ", " In my opinion ", df, ignore.case = TRUE)
        df = gsub(" IRL ", " In real life ", df, ignore.case = TRUE)
        df = gsub(" IU2U ", " It’s up to you ", df, ignore.case = TRUE)
        df = gsub(" IYKWIM ", " If you know what I mean ", df, ignore.case = TRUE)
        df = gsub(" J/K ", " Just kidding ", df, ignore.case = TRUE)
        df = gsub(" J4F ", " Just for fun ", df, ignore.case = TRUE)
        df = gsub(" JIC ", " Just in case ", df, ignore.case = TRUE)
        df = gsub(" JSYK ", " Just so you know ", df, ignore.case = TRUE)
        df = gsub(" K or KK ", " Okay ", df, ignore.case = TRUE)
        df = gsub(" LMBO ", " Laughing my butt off ", df, ignore.case = TRUE)
        df = gsub(" LMK ", " Let me know ", df, ignore.case = TRUE)
        df = gsub(" LOL ", " Laughing out loud ", df, ignore.case = TRUE)
        df = gsub(" MM ", " Music Monday ", df, ignore.case = TRUE)
        df = gsub(" MSM ", " Mainstream media ", df, ignore.case = TRUE)
        df = gsub(" NAGI ", " Not a good idea ", df, ignore.case = TRUE)
        df = gsub(" NM ", " Never mind ", df, ignore.case = TRUE)
        df = gsub(" NMU ", " Not much, you? ", df, ignore.case = TRUE)
        df = gsub(" NP ", " No problem ", df, ignore.case = TRUE)
        df = gsub(" NSFW ", " Not safe for work ", df, ignore.case = TRUE)
        df = gsub(" NSFL ", " Not safe for life ", df, ignore.case = TRUE)
        df = gsub(" OH ", " Overheard ", df, ignore.case = TRUE)
        df = gsub(" OMG ", " Oh my God ", df, ignore.case = TRUE)
        df = gsub(" ORLY ", " Oh, really? ", df, ignore.case = TRUE)
        df = gsub(" PAW ", " Parents are watching ", df, ignore.case = TRUE)
        df = gsub(" PLS ", " Please ", df, ignore.case = TRUE)
        df = gsub(" PLZ ", " Please ", df, ignore.case = TRUE)
        df = gsub(" PPL ", " People ", df, ignore.case = TRUE)
        df = gsub(" PTB ", " Please text back ", df, ignore.case = TRUE)
        df = gsub(" QQ ", " Crying ", df, ignore.case = TRUE)
        df = gsub(" RAK ", " Random act of kindness ", df, ignore.case = TRUE)
        df = gsub(" RL ", " Real life ", df, ignore.case = TRUE)
        df = gsub(" ROFL ", " Rolling on the floor laughing ", df, ignore.case = TRUE)
        df = gsub(" RT ", " Retweet ", df, ignore.case = TRUE)
        df = gsub(" RUOK ", " Are you okay? ", df, ignore.case = TRUE)
        df = gsub(" SMH ", " Shaking my head ", df, ignore.case = TRUE)
        df = gsub(" SRSLY ", " Seriously ", df, ignore.case = TRUE)
        df = gsub(" SSDD ", " Same stuff, different day ", df, ignore.case = TRUE)
        df = gsub(" SWAK ", " Sealed with a kiss ", df, ignore.case = TRUE)
        df = gsub(" SWYP ", " So, what’s your problem? ", df, ignore.case = TRUE)
        df = gsub(" TIA ", " Thanks in advance ", df, ignore.case = TRUE)
        df = gsub(" TIME ", " Tears in my eyes ", df, ignore.case = TRUE)
        df = gsub(" TMB ", " Tweet me back ", df, ignore.case = TRUE)
        df = gsub(" TMI ", " Too much information ", df, ignore.case = TRUE)
        df = gsub(" TMRW ", " Tomorrow ", df, ignore.case = TRUE)
        df = gsub(" TTYL ", " Talk to you later ", df, ignore.case = TRUE)
        df = gsub(" TY or TU ", " Thank you ", df, ignore.case = TRUE)
        df = gsub(" VSF ", " Very sad face ", df, ignore.case = TRUE)
        df = gsub(" WB ", " Welcome back ", df, ignore.case = TRUE)
        df = gsub(" WTH ", " What the heck? ", df, ignore.case = TRUE)
        df = gsub(" WTPA ", " Where the party at? ", df, ignore.case = TRUE)
        df = gsub(" WYCM ", " Will you call me? ", df, ignore.case = TRUE)
        df = gsub(" YGM ", " You’ve got mail ", df, ignore.case = TRUE)
        df = gsub(" YMMV ", " Your mileage may vary ", df, ignore.case = TRUE)
        df = gsub(" YW ", " You’re welcome ", df, ignore.case = TRUE)
        df = gsub(" ZOMG ", " Oh my god ", df, ignore.case = TRUE)
        
        df = gsub(" ABT ", " About ", df,  ignore.case = TRUE)
        df = gsub(" ABT2 ", " About to ", df, ignore.case = TRUE)
        df = gsub(" ACDNT ", " Accident ", df, ignore.case = TRUE)
        df = gsub(" ACK ", " Acknowledge ", df, ignore.case = TRUE)
        df = gsub(" ACPT ", " Accept ", df, ignore.case = TRUE)
        df = gsub(" ADD ", " Address ", df, ignore.case = TRUE)
        df = gsub(" ADDY ", " Address ", df, ignore.case = TRUE)
        df = gsub(" AEAP ", " As early as possible ", df, ignore.case = TRUE)
        df = gsub(" AF ", " April Fools ", df, ignore.case = TRUE)
        df = gsub(" AFK ", " Away from keyboard ", df, ignore.case = TRUE)
        df = gsub(" AIGHT ", " Alright ", df, ignore.case = TRUE)
        df = gsub(" AKA ", " Also known as ", df, ignore.case = TRUE)
        df = gsub(" AMAP ", " As much as possible ", df, ignore.case = TRUE)
        df = gsub(" AML ", " All my love ", df, ignore.case = TRUE)
        df = gsub(" AMOF ", " As a matter of fact ", df, ignore.case = TRUE)
        df = gsub(" ASAP ", " As soon as possible ", df, ignore.case = TRUE)
        df = gsub(" ATB ", " All the best ", df, ignore.case = TRUE)
        df = gsub(" ATEOTD ", " At the end of the day ", df, ignore.case = TRUE)
        df = gsub(" AYT ", " Are you there? ", df, ignore.case = TRUE)
        df = gsub(" B2W ", " Back to work ", df, ignore.case = TRUE)
        df = gsub(" B4 ", " Before ", df, ignore.case = TRUE)
        df = gsub(" BDAY ", " Birthday ", df, ignore.case = TRUE)
        df = gsub(" BF ", " Boyfriend ", df, ignore.case = TRUE)
        df = gsub(" BF ", " Best friend ", df, ignore.case = TRUE)
        df = gsub(" BF4L ", " Best friend for life ", df, ignore.case = TRUE)
        df = gsub(" BFF ", " Best friends forever ", df, ignore.case = TRUE)
        df = gsub(" BLNT ", " Better luck next time ", df, ignore.case = TRUE)
        df = gsub(" BM ", " Bite me ", df, ignore.case = TRUE)
        df = gsub(" BOYF ", " Boyfriend ", df, ignore.case = TRUE)
        df = gsub(" BRB ", " Be right back ", df, ignore.case = TRUE)
        df = gsub(" BTW ", " By the Way ", df, ignore.case = TRUE)
        df = gsub(" BYOB ", " Bring Your Own beer ", df, ignore.case = TRUE)
        df = gsub(" CIAO ", " Good-bye ", df, ignore.case = TRUE)
        df = gsub(" CM ", " Call me ", df, ignore.case = TRUE)
        df = gsub(" CMB ", " Call me back ", df, ignore.case = TRUE)
        df = gsub(" CMON ", " Come on ", df, ignore.case = TRUE)
        df = gsub(" CR8 ", " Create ", df, ignore.case = TRUE)
        df = gsub(" CTC ", " Care to chat? ", df, ignore.case = TRUE)
        df = gsub(" CU ", " See you ", df, ignore.case = TRUE)
        df = gsub(" CUA ", " See you around ", df, ignore.case = TRUE)
        df = gsub(" CUL ", " See you later ", df, ignore.case = TRUE)
        df = gsub(" CUL8R ", " See you later ", df, ignore.case = TRUE)
        df = gsub(" CYA ", " See you ", df, ignore.case = TRUE)
        df = gsub(" CYAL8R ", " See you later ", df, ignore.case = TRUE)
        df = gsub(" DOS ", " Dad over shoulder ", df, ignore.case = TRUE)
        df = gsub(" DIY ", " Do it yourself ", df, ignore.case = TRUE)
        df = gsub(" DKDC ", " Don’t know, don’t care ", df, ignore.case = TRUE)
        df = gsub(" D/L ", " Download ", df, ignore.case = TRUE)
        df = gsub(" DL ", " Download ", df, ignore.case = TRUE)
        df = gsub(" DNT ", " Don’t ", df, ignore.case = TRUE)
        df = gsub(" EMA ", " E-mail address ", df, ignore.case = TRUE)
        df = gsub(" EOM ", " End of message ", df, ignore.case = TRUE)
        df = gsub(" ETA ", " Estimated time of arrival ", df, ignore.case = TRUE)
        df = gsub(" EZ ", " Easy ", df, ignore.case = TRUE)
        df = gsub(" EZY ", " Easy ", df, ignore.case = TRUE)
        df = gsub(" FAQ ", " Frequently asked questions ", df, ignore.case = TRUE)
        df = gsub(" FBM ", " Fine by me ", df, ignore.case = TRUE)
        df = gsub(" FC ", " Fingers crossed ", df, ignore.case = TRUE)
        df = gsub(" FTW ", " For the win ", df, ignore.case = TRUE)
        df = gsub(" FW ", " Forward ", df, ignore.case = TRUE)
        df = gsub(" FWIW ", " For what it’s worth ", df, ignore.case = TRUE)
        df = gsub(" FWM ", " Fine with me ", df, ignore.case = TRUE)
        df = gsub(" FYEO ", " For your eyes only ", df, ignore.case = TRUE)
        df = gsub(" FYA ", " For your amusement ", df, ignore.case = TRUE)
        df = gsub(" FYI ", " For your information ", df, ignore.case = TRUE)
        df = gsub(" G ", " Giggle ", df, ignore.case = TRUE)
        df = gsub(" G2CU ", " Good to see you ", df, ignore.case = TRUE)
        df = gsub(" G2G ", " Got to go ", df, ignore.case = TRUE)
        df = gsub(" G2R ", " Got to run ", df, ignore.case = TRUE)
        df = gsub(" GB ", " Goodbye ", df, ignore.case = TRUE)
        df = gsub(" GBTW ", " Get back to work ", df, ignore.case = TRUE)
        df = gsub(" GBU ", " God bless you ", df, ignore.case = TRUE)
        df = gsub(" GF ", " Girl friend ", df, ignore.case = TRUE)
        df = gsub(" GG ", " Gotta Go ", df, ignore.case = TRUE)
        df = gsub(" GJ ", " Good job ", df, ignore.case = TRUE)
        df = gsub(" GL ", " Good luck ", df, ignore.case = TRUE)
        df = gsub(" GMTA ", " Great minds thing alike ", df, ignore.case = TRUE)
        df = gsub(" GN ", " Good night ", df, ignore.case = TRUE)
        df = gsub(" GNIGHT ", " Good night ", df, ignore.case = TRUE)
        df = gsub(" GNITE ", " Good night ", df, ignore.case = TRUE)
        df = gsub(" GR8 ", " Great ", df, ignore.case = TRUE)
        df = gsub(" GRATZ ", " Congratulations ", df, ignore.case = TRUE)
        df = gsub(" GTG ", " Got to go ", df, ignore.case = TRUE)
        df = gsub(" GUD ", " Good ", df, ignore.case = TRUE)
        df = gsub(" GUDNYT ", " Goodnight ", df, ignore.case = TRUE)
        df = gsub(" H8 ", " Hate ", df, ignore.case = TRUE)
        df = gsub(" HAK ", " Hug and kiss ", df, ignore.case = TRUE)
        df = gsub(" HAU ", " How about you? ", df, ignore.case = TRUE)
        df = gsub(" HAV ", " Have ", df, ignore.case = TRUE)
        df = gsub(" H&K ", " Hugs & kisses ", df, ignore.case = TRUE)
        df = gsub(" H2CUS ", " Hope to see you soon ", df, ignore.case = TRUE)
        df = gsub(" HAND ", " Have a nice day ", df, ignore.case = TRUE)
        df = gsub(" H-BDAY ", " Happy Birthday ", df, ignore.case = TRUE)
        df = gsub(" HF ", " Have fun ", df, ignore.case = TRUE)
        df = gsub(" HFAC ", " Holy flipping animal crackers ", df, ignore.case = TRUE)
        df = gsub(" HRU ", " How are you? ", df, ignore.case = TRUE)
        df = gsub(" HTH ", " Hope this helps ", df, ignore.case = TRUE)
        df = gsub(" HUB ", " Head up butt ", df, ignore.case = TRUE)
        df = gsub(" HUYA ", " Head up your ass ", df, ignore.case = TRUE)
        df = gsub(" HV ", " Have ", df, ignore.case = TRUE)
        df = gsub(" HW ", " Homework ", df, ignore.case = TRUE)
        df = gsub(" IB ", " I’m back ", df, ignore.case = TRUE)
        df = gsub(" IC ", " I see ", df, ignore.case = TRUE)
        df = gsub(" IDC ", " I don’t care ", df, ignore.case = TRUE)
        df = gsub(" IHNI ", " I have no idea ", df, ignore.case = TRUE)
        df = gsub(" IK ", " I know ", df, ignore.case = TRUE)
        df = gsub(" ILU ", " I love you ", df, ignore.case = TRUE)
        df = gsub(" ILY ", " I love you ", df, ignore.case = TRUE)
        df = gsub(" IM ", " Instant message ", df, ignore.case = TRUE)
        df = gsub(" IMHO ", " In my humble opinion ", df, ignore.case = TRUE)
        df = gsub(" IMO ", " In my opinion ", df, ignore.case = TRUE)
        df = gsub(" IMS ", " I am sorry ", df, ignore.case = TRUE)
        df = gsub(" IMU ", " I miss you ", df, ignore.case = TRUE)
        df = gsub(" IRL ", " In real life ", df, ignore.case = TRUE)
        df = gsub(" IUSS ", " If you say so ", df, ignore.case = TRUE)
        df = gsub(" JAC ", " Just a sec ", df, ignore.case = TRUE)
        df = gsub(" JK ", " Just kidding ", df, ignore.case = TRUE)
        df = gsub(" JLMK ", " Just let me know ", df, ignore.case = TRUE)
        df = gsub(" K ", " Okay ", df, ignore.case = TRUE)
        df = gsub(" KK ", " Okay Okay! ", df, ignore.case = TRUE)
        df = gsub(" KEWL ", " Cool ", df, ignore.case = TRUE)
        df = gsub(" KIT ", " Keep in touch ", df, ignore.case = TRUE)
        df = gsub(" KUTGW ", " Keep up the good work ", df, ignore.case = TRUE)
        df = gsub(" L8R ", " Later ", df, ignore.case = TRUE)
        df = gsub(" LOL ", " Laugh out loud ", df, ignore.case = TRUE)
        df = gsub(" LOL ", " Lots of love ", df, ignore.case = TRUE)
        df = gsub(" LTNS ", " long time no see ", df, ignore.case = TRUE)
        df = gsub(" LUVYA ", " Love you ", df, ignore.case = TRUE)
        df = gsub(" MC ", " Merry Christmas ", df, ignore.case = TRUE)
        df = gsub(" MOS ", " Mother over shoulder ", df, ignore.case = TRUE)
        df = gsub(" MIRL ", " Meet in real life ", df, ignore.case = TRUE)
        df = gsub(" MKAY ", " Mmm okay ", df, ignore.case = TRUE)
        df = gsub(" MSG ", " Message ", df, ignore.case = TRUE)
        df = gsub(" MTF ", " More to follow ", df, ignore.case = TRUE)
        df = gsub(" MUSM ", " Miss you so much ", df, ignore.case = TRUE)
        df = gsub(" MWAH ", " To give a kiss ", df, ignore.case = TRUE)
        df = gsub(" MYOB ", " Mind your own business ", df, ignore.case = TRUE)
        df = gsub(" N1 ", " Nice one ", df, ignore.case = TRUE)
        df = gsub(" N2M ", " Nothing too much ", df, ignore.case = TRUE)
        df = gsub(" NBD ", " No big deal ", df, ignore.case = TRUE)
        df = gsub(" NE ", " Any ", df, ignore.case = TRUE)
        df = gsub(" NE1 ", " Anyone ", df, ignore.case = TRUE)
        df = gsub(" NIMBY ", " Not in my back yard ", df, ignore.case = TRUE)
        df = gsub(" NM ", " Nothing much ", df, ignore.case = TRUE)
        df = gsub(" NM ", " Never mind ", df, ignore.case = TRUE)
        df = gsub(" NOYB ", " None of your business ", df, ignore.case = TRUE)
        df = gsub(" NP ", " No problem ", df, ignore.case = TRUE)
        df = gsub(" NT ", " Nice try ", df, ignore.case = TRUE)
        df = gsub(" NVM ", " Never mind ", df, ignore.case = TRUE)
        df = gsub(" NVR ", " Never ", df, ignore.case = TRUE)
        df = gsub(" NW ", " No way ", df, ignore.case = TRUE)
        df = gsub(" OB ", " Oh baby ", df, ignore.case = TRUE)
        df = gsub(" OB ", " Oh brother ", df, ignore.case = TRUE)
        df = gsub(" OI ", " Operator indisposed ", df, ignore.case = TRUE)
        df = gsub(" OIC ", " Oh I see ", df, ignore.case = TRUE)
        df = gsub(" OJ ", " Only joking ", df, ignore.case = TRUE)
        df = gsub(" OM ", " Oh my ", df, ignore.case = TRUE)
        df = gsub(" OMDB ", " Over my dead body ", df, ignore.case = TRUE)
        df = gsub(" OMG ", " Oh my God ", df, ignore.case = TRUE)
        df = gsub(" OMW ", " On my way ", df, ignore.case = TRUE)
        df = gsub(" ONL ", " Online ", df, ignore.case = TRUE)
        df = gsub(" OTB ", " Off to bed ", df, ignore.case = TRUE)
        df = gsub(" OTL ", " Out to lunch ", df, ignore.case = TRUE)
        df = gsub(" OTOH ", " On the other hand ", df, ignore.case = TRUE)
        df = gsub(" OVA ", " Over ", df, ignore.case = TRUE)
        df = gsub(" P2P ", " Peer to peer ", df, ignore.case = TRUE)
        df = gsub(" PEEPS ", " People ", df, ignore.case = TRUE)
        df = gsub(" PIC ", " Picture ", df, ignore.case = TRUE)
        df = gsub(" PL8 ", " Plate ", df, ignore.case = TRUE)
        df = gsub(" PLMK ", " Please let me know ", df, ignore.case = TRUE)
        df = gsub(" PLS ", " Please ", df, ignore.case = TRUE)
        df = gsub(" PLZ ", " Please ", df, ignore.case = TRUE)
        df = gsub(" PM ", " Private Message ", df, ignore.case = TRUE)
        df = gsub(" POS ", " Parent over shoulder ", df, ignore.case = TRUE)
        df = gsub(" POV ", " Point of view ", df, ignore.case = TRUE)
        df = gsub(" PPL ", " People ", df, ignore.case = TRUE)
        df = gsub(" PROLLY ", " Probably ", df, ignore.case = TRUE)
        df = gsub(" PRT ", " Party ", df, ignore.case = TRUE)
        df = gsub(" PZ ", " Peace ", df, ignore.case = TRUE)
        df = gsub(" QIK ", " Quick ", df, ignore.case = TRUE)
        df = gsub(" QL ", " Quit laughing ", df, ignore.case = TRUE)
        df = gsub(" QT ", " Cutie ", df, ignore.case = TRUE)
        df = gsub(" QTPI ", " Cutie pie ", df, ignore.case = TRUE)
        df = gsub(" RIP ", " Rest in peace ", df, ignore.case = TRUE)
        df = gsub(" RLY ", " Really ", df, ignore.case = TRUE)
        df = gsub(" RME ", " Rolling my eyes ", df, ignore.case = TRUE)
        df = gsub(" ROFLOL ", " Rolling on floor  laughing out loud ", df, ignore.case = TRUE)
        df = gsub(" RU ", " Are you? ", df, ignore.case = TRUE)
        df = gsub(" RUOK ", " Are you okay? ", df, ignore.case = TRUE)
        df = gsub(" RX ", " Regards ", df, ignore.case = TRUE)
        df = gsub(" SBT ", " Sorry ’bout that ", df, ignore.case = TRUE)
        df = gsub(" SC ", " Stay cool ", df, ignore.case = TRUE)
        df = gsub(" SIT ", " Stay in touch ", df, ignore.case = TRUE)
        df = gsub(" SK8 ", " Skate ", df, ignore.case = TRUE)
        df = gsub(" SK8NG ", " Skating ", df, ignore.case = TRUE)
        df = gsub(" SK8R ", " Skater ", df, ignore.case = TRUE)
        df = gsub(" SK8RBOI ", " Skater Boy ", df, ignore.case = TRUE)
        df = gsub(" SO ", " Significant other ", df, ignore.case = TRUE)
        df = gsub(" SOAB ", " Son of a B*tch ", df, ignore.case = TRUE)
        df = gsub(" SOL ", " Sooner or later ", df, ignore.case = TRUE)
        df = gsub(" SOS ", " Meaning help ", df, ignore.case = TRUE)
        df = gsub(" SRSLY ", " Seriously ", df, ignore.case = TRUE)
        df = gsub(" SRY ", " Sorry ", df, ignore.case = TRUE)
        df = gsub(" SS ", " So sorry ", df, ignore.case = TRUE)
        df = gsub(" STR8 ", " Straight ", df, ignore.case = TRUE)
        df = gsub(" SUL ", " See you later ", df, ignore.case = TRUE)
        df = gsub(" SUP ", " What’s up? ", df, ignore.case = TRUE)
        df = gsub(" SUX ", " sucks or “it sucks” ", df, ignore.case = TRUE)
        df = gsub(" SYL ", " See you later ", df, ignore.case = TRUE)
        df = gsub(" SYS ", " See you soon ", df, ignore.case = TRUE)
        df = gsub(" TBC ", " To be continued ", df, ignore.case = TRUE)
        df = gsub(" TBD ", " To be determined ", df, ignore.case = TRUE)
        df = gsub(" TBL ", " Text back later ", df, ignore.case = TRUE)
        df = gsub(" TC ", " Take care ", df, ignore.case = TRUE)
        df = gsub(" TGIF ", " Thank God it’s Friday ", df, ignore.case = TRUE)
        df = gsub(" THX ", " Thanks ", df, ignore.case = TRUE)
        df = gsub(" THNX ", " Thanks ", df, ignore.case = TRUE)
        df = gsub(" TMB ", " Text me back ", df, ignore.case = TRUE)
        df = gsub(" TMI ", " Too much information ", df, ignore.case = TRUE)
        df = gsub(" TMTH ", " Too much to handle ", df, ignore.case = TRUE)
        df = gsub(" TOJ ", " Tears of joy ", df, ignore.case = TRUE)
        df = gsub(" TTFN ", " Ta ta for now ", df, ignore.case = TRUE)
        df = gsub(" TTLY ", " Totally ", df, ignore.case = TRUE)
        df = gsub(" TTUL ", " Talk to you later ", df, ignore.case = TRUE)
        df = gsub(" TU ", " Thank you ", df, ignore.case = TRUE)
        df = gsub(" TTYL ", " Talk to you later ", df, ignore.case = TRUE)
        df = gsub(" TTYS ", " Talk to you soon ", df, ignore.case = TRUE)
        df = gsub(" TY ", " Thank you ", df, ignore.case = TRUE)
        df = gsub(" UFB ", " Un freaking believable ", df, ignore.case = TRUE)
        df = gsub(" UFN ", " Until further notice ", df, ignore.case = TRUE)
        df = gsub(" UL ", " Upload ", df, ignore.case = TRUE)
        df = gsub(" U-L ", " You will ", df, ignore.case = TRUE)
        df = gsub(" UOK ", " You ok? ", df, ignore.case = TRUE)
        df = gsub(" UR ", " Your ", df, ignore.case = TRUE)
        df = gsub(" URW ", " You are welcome ", df, ignore.case = TRUE)
        df = gsub(" UW ", " You’re welcome ", df, ignore.case = TRUE)
        df = gsub(" VBS ", " Very big smile ", df, ignore.case = TRUE)
        df = gsub(" VIP ", " Very important person ", df, ignore.case = TRUE)
        df = gsub(" VM ", " Voice mail ", df, ignore.case = TRUE)
        df = gsub(" VN ", " Very nice ", df, ignore.case = TRUE)
        df = gsub(" VRY ", " Very ", df, ignore.case = TRUE)
        df = gsub(" W@ ", " What? ", df, ignore.case = TRUE)
        df = gsub(" W/ ", " With ", df, ignore.case = TRUE)
        df = gsub(" W8 ", " Wait ", df, ignore.case = TRUE)
        df = gsub(" WAH ", " Working at home ", df, ignore.case = TRUE)
        df = gsub(" WAM ", " Wait a minute ", df, ignore.case = TRUE)
        df = gsub(" WAYF ", " Where are you from? ", df, ignore.case = TRUE)
        df = gsub(" W/B ", " Write back ", df, ignore.case = TRUE)
        df = gsub(" WB ", " Welcome back ", df, ignore.case = TRUE)
        df = gsub(" WBU ", " What about you? ", df, ignore.case = TRUE)
        df = gsub(" WC ", " Who cares ", df, ignore.case = TRUE)
        df = gsub(" W/E ", " Whatever ", df, ignore.case = TRUE)
        df = gsub(" W/END ", " Weekend ", df, ignore.case = TRUE)
        df = gsub(" WE ", " Whatever ", df, ignore.case = TRUE)
        df = gsub(" WIU ", " Wrap it up ", df, ignore.case = TRUE)
        df = gsub(" WK ", " Week ", df, ignore.case = TRUE)
        df = gsub(" WKD ", " Weekend ", df, ignore.case = TRUE)
        df = gsub(" W/O ", " Without ", df, ignore.case = TRUE)
        df = gsub(" WRK ", " Work ", df, ignore.case = TRUE)
        df = gsub(" WRU@ ", " Where are you at? ", df, ignore.case = TRUE)
        df = gsub(" WTF ", " What the freak ", df, ignore.case = TRUE)
        df = gsub(" WTG ", " Way to go ", df, ignore.case = TRUE)
        df = gsub(" WTH ", " What the heck? What the hell? ", df, ignore.case = TRUE)
        df = gsub(" WTM ", " Who’s the man? ", df, ignore.case = TRUE)
        df = gsub(" WU ", " What’s up? ", df, ignore.case = TRUE)
        df = gsub(" WUF ", " Where are you from? ", df, ignore.case = TRUE)
        df = gsub(" WUP ", " What’s up? ", df, ignore.case = TRUE)
        df = gsub(" X ", " Kiss ", df, ignore.case = TRUE)
        df = gsub(" XME ", " Excuse Me ", df, ignore.case = TRUE)
        df = gsub(" XOXOXO ", " Hugs and Kisses ", df, ignore.case = TRUE)
        df = gsub(" XLNT ", " Excellent ", df, ignore.case = TRUE)
        df = gsub(" Y? ", " Why? ", df, ignore.case = TRUE)
        df = gsub(" Y2K ", " You’re too kind ", df, ignore.case = TRUE)
        df = gsub(" YARLY ", " Ya really? ", df, ignore.case = TRUE)
        df = gsub(" YBS ", " You’ll be sorry ", df, ignore.case = TRUE)
        df = gsub(" YGG ", " You go girl ", df, ignore.case = TRUE)
        df = gsub(" YNK ", " You never know ", df, ignore.case = TRUE)
        df = gsub(" YR ", " Your ", df, ignore.case = TRUE)
        df = gsub(" YR ", " Yeah right ", df, ignore.case = TRUE)
        df = gsub(" YW ", " You’re welcome ", df, ignore.case = TRUE)
        df = gsub(" ZUP ", " What’s up ? ", df, ignore.case = TRUE)
        df = gsub(" ZZZZ ", " Bored ", df, ignore.case = TRUE)
        df = gsub(" D'aww ", " Awww ", df, ignore.case = TRUE)
        return(rm_white(tolower(df)))
        
}

